"""empty message

Revision ID: 0f8a23484462
Revises: 9dc6a44d66da
Create Date: 2023-09-28 21:33:26.012030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8a23484462'
down_revision = '9dc6a44d66da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafeterias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('breakfast_start_time', sa.Time(), nullable=True),
    sa.Column('breakfast_end_time', sa.Time(), nullable=True),
    sa.Column('lunch_start_time', sa.Time(), nullable=True),
    sa.Column('lunch_end_time', sa.Time(), nullable=True),
    sa.Column('dinner_start_time', sa.Time(), nullable=True),
    sa.Column('dinner_end_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('file_url', sa.String(length=200), nullable=False),
    sa.Column('html_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('diets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=500), nullable=False),
    sa.Column('img_path', sa.String(length=500), nullable=False),
    sa.Column('post_title', sa.String(length=200), nullable=False),
    sa.Column('post_create_date', sa.DateTime(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('cafeteria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cafeteria_id'], ['cafeterias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cafeteria')
    op.drop_table('diet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('img_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('img_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('post_title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('post_create_date', sa.DATETIME(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('update_date', sa.DATETIME(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('cafeteria_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cafeteria_id'], ['cafeteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cafeteria',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('location', sa.VARCHAR(length=50), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('update_date', sa.DATETIME(), nullable=False),
    sa.Column('breakfast_start_time', sa.TIME(), nullable=True),
    sa.Column('breakfast_end_time', sa.TIME(), nullable=True),
    sa.Column('lunch_start_time', sa.TIME(), nullable=True),
    sa.Column('lunch_end_time', sa.TIME(), nullable=True),
    sa.Column('dinner_start_time', sa.TIME(), nullable=True),
    sa.Column('dinner_end_time', sa.TIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('diets')
    op.drop_table('regulations')
    op.drop_table('cafeterias')
    # ### end Alembic commands ###
