"""empty message

Revision ID: 9dc6a44d66da
Revises: 
Create Date: 2023-09-28 10:45:25.394743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc6a44d66da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafeteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('breakfast_start_time', sa.Time(), nullable=True),
    sa.Column('breakfast_end_time', sa.Time(), nullable=True),
    sa.Column('lunch_start_time', sa.Time(), nullable=True),
    sa.Column('lunch_end_time', sa.Time(), nullable=True),
    sa.Column('dinner_start_time', sa.Time(), nullable=True),
    sa.Column('dinner_end_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=500), nullable=False),
    sa.Column('img_path', sa.String(length=500), nullable=False),
    sa.Column('post_title', sa.String(length=200), nullable=False),
    sa.Column('post_create_date', sa.DateTime(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('cafeteria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cafeteria_id'], ['cafeteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diet')
    op.drop_table('cafeteria')
    # ### end Alembic commands ###
