"""empty message

Revision ID: a6017f92ae1e
Revises: 0f8a23484462
Create Date: 2023-10-06 17:44:54.433671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6017f92ae1e'
down_revision = '0f8a23484462'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('법', '시행령', '시행규칙', '정관', '조례', '예규', '규정', '내규'), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('enforce_date', sa.DateTime(), nullable=True),
    sa.Column('file_url', sa.String(length=200), nullable=True),
    sa.Column('html_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regulations')
    # ### end Alembic commands ###
